### ISSUE TITLE
facebook login internal server error

### ISSUE THREAD

**Issue by brenca** [hapijs/bell#112]
When I try to use the facebook strategy, I get the following error:

```
Debug: auth, unauthenticated, error, facebook
    Error: Missing facebook request token cookie
    at Object.exports.create (D:\Info\coven-sso\node_modules\bell\node_modules\b
oom\lib\index.js:21:17)
    at Object.exports.internal (D:\Info\coven-sso\node_modules\bell\node_modules
\boom\lib\index.js:262:99)
    at Object.authenticate (D:\Info\coven-sso\node_modules\bell\lib\oauth.js:177
:31)
    at D:\Info\coven-sso\node_modules\hapi\lib\auth.js:227:30
    at internals.Protect.run (D:\Info\coven-sso\node_modules\hapi\lib\protect.js
:56:5)
    at authenticate (D:\Info\coven-sso\node_modules\hapi\lib\auth.js:218:26)
    at internals.Auth._authenticate (D:\Info\coven-sso\node_modules\hapi\lib\aut
h.js:348:5)
    at internals.Auth.authenticate (D:\Info\coven-sso\node_modules\hapi\lib\auth
.js:177:17)
    at D:\Info\coven-sso\node_modules\hapi\lib\request.js:370:13
    at iterate (D:\Info\coven-sso\node_modules\hapi\node_modules\items\lib\index
.js:35:13)
Debug: internal, error
    Error: Missing facebook request token cookie
    at Object.exports.create (D:\Info\coven-sso\node_modules\bell\node_modules\b
oom\lib\index.js:21:17)
    at Object.exports.internal (D:\Info\coven-sso\node_modules\bell\node_modules
\boom\lib\index.js:262:99)
    at Object.authenticate (D:\Info\coven-sso\node_modules\bell\lib\oauth.js:177
:31)
    at D:\Info\coven-sso\node_modules\hapi\lib\auth.js:227:30
    at internals.Protect.run (D:\Info\coven-sso\node_modules\hapi\lib\protect.js
:56:5)
    at authenticate (D:\Info\coven-sso\node_modules\hapi\lib\auth.js:218:26)
    at internals.Auth._authenticate (D:\Info\coven-sso\node_modules\hapi\lib\aut
h.js:348:5)
    at internals.Auth.authenticate (D:\Info\coven-sso\node_modules\hapi\lib\auth
.js:177:17)
    at D:\Info\coven-sso\node_modules\hapi\lib\request.js:370:13
    at iterate (D:\Info\coven-sso\node_modules\hapi\node_modules\items\lib\index
.js:35:13)
```

Here's my code (basicly your twitter example)

```javascript
var Hapi = require('hapi');

var server = new Hapi.Server({ debug: { request: ['error'] } });
server.connection({ port: 3000 });

server.register(require('bell'), function (err) {

    server.auth.strategy('facebook', 'bell', {
        provider: 'facebook',
        password: 'test',
        clientId: '',
        clientSecret: '',
        isSecure: false
    });

    server.route({
        method: ['GET', 'POST'],
        path: '/login',
        config: {
            auth: 'facebook',
            handler: function (request, reply) {

                if (!request.auth.isAuthenticated) {
                    return reply('Authentication failed due to: ' + request.auth.error.message);
                }

                return reply.redirect('/home');
            }
        }
    });

    server.route({
        method: ['GET'],
        path: '/home',
        config: {
            handler: function (request, reply) {
                console.log(request.auth.credentials);
                return reply(JSON.stringify(request.auth.credentials));
            }
        }
    });

    server.start(function () {
        console.log('Server running at:', server.info.uri);
    });
});
```

**Comment by asilluron** [comment]
Had the exact same issue. I downgraded to version: ^3.0.0 and it worked again.

**Comment by rainabba** [comment]
I was getting a token error, set package.json to <4.0.0 and now i'm good. Definitely something broken in 4.0.0.

**Comment by geuis** [comment]
This commit is not in the version installed by npm, https://github.com/hapijs/bell/commit/a30a85b321d685718ef5726dc08ed0d6dffbe25d.

**Comment by Gouthamve** [comment]
Yes, I too am getting a token error in 4.0.0. Here is my stack:

```
Debug: auth, unauthenticated, error, fb 
    Error: Failed obtaining facebook access token
    at Object.exports.create (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/boom/lib/index.js:262:99)
    at /Users/goutham/adiStuff/labs-api/node_modules/bell/lib/oauth.js:224:35
    at /Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:454:20
    at finish (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:284:20)
    at wrapped (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/hoek/lib/index.js:808:20)
    at onReaderFinish (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:346:16)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
Debug: internal, error 
    Error: Failed obtaining facebook access token
    at Object.exports.create (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/boom/lib/index.js:262:99)
    at /Users/goutham/adiStuff/labs-api/node_modules/bell/lib/oauth.js:224:35
    at /Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:454:20
    at finish (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:284:20)
    at wrapped (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/hoek/lib/index.js:808:20)
    at onReaderFinish (/Users/goutham/adiStuff/labs-api/node_modules/bell/node_modules/wreck/lib/index.js:346:16)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
```

**Comment by phoenixbox** [comment]
Downgraded to `^3.0.0` and it works :+1:

**Comment by jakegibson** [comment]
.. Should have checked here sooner.  Seems to not be passing the client secret in 4.0.0

**Comment by jakegibson** [comment]
https://github.com/hapijs/bell/issues/102

**Comment by brenca** [comment]
When I posted this issue, the one you referred to was closed, so I didn't think that that still was the cause.
