### ISSUE TITLE
Bug: Missing facebook request token cookie on reload popup window

### ISSUE THREAD

**Issue by thebillkidy** [hapijs/bell#175]
When we reload the popup window of Facebook we get a "Missing facebook request token cookie" error.

The stacktrace:

```
Debug: auth, unauthenticated, error, facebook
    Error: Missing facebook request token cookie
    at Object.authenticate (C:\Projects\undefined\Backend\node_modules\bell\lib\oauth.js:191:31)
    at C:\Projects\undefined\Backend\node_modules\hapi\lib\auth.js:324:34
    at internals.Protect.run.finish [as run] (C:\Projects\undefined\Backend\node_modules\hapi\lib\protect.js:64:5)
    at execute (C:\Projects\undefined\Backend\node_modules\hapi\lib\auth.js:320:30)
    at authenticate (C:\Projects\undefined\Backend\node_modules\hapi\lib\auth.js:306:21)
    at internals.Auth.test.internals.Auth._authenticate (C:\Projects\undefined\Backend\node_modules\hapi\lib\auth.js:214:19)
    at internals.Auth.test.internals.Auth.authenticate (C:\Projects\undefined\Backend\node_modules\hapi\lib\auth.js:202:17)
    at each (C:\Projects\undefined\Backend\node_modules\hapi\lib\request.js:383:16)
    at iterate (C:\Projects\undefined\Backend\node_modules\hapi\node_modules\items\lib\index.js:36:13)
    at done (C:\Projects\undefined\Backend\node_modules\hapi\node_modules\items\lib\index.js:28:25)
    at C:\Projects\undefined\Backend\node_modules\hapi\lib\route.js:386:20
    at C:\Projects\undefined\Backend\node_modules\hapi\node_modules\statehood\lib\index.js:242
```

**Comment by thebillkidy** [comment]
Nvm, can be solved. Just saw that this error gets handled in the library and that we should catch it. Sorry for this
