### ISSUE TITLE
Error configuring google login

### ISSUE THREAD

**Issue by lfsmoura** [hapijs/bell#238]
I recently updated hapi and bell and I'm having an error when I use this:

        server.auth.strategy('google', 'bell', {
            provider: 'google',
            location: server.info.uri,
            password: config.COOKIE_PASSWORD,
            clientId: config.GOOGLE_CLIENT_ID,
            clientSecret: config.GOOGLE_CLIENT_SECRET,
            // required if not using HTTPS especially if developing locally
            isSecure: false
        });

The error is the following:
Unhandled rejection TypeError: Map is not a constructor
    at Object.exports.clone (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/hoek/lib/index.js:26:20)
    at Object.exports.cloneWithShallow (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/hoek/lib/index.js:181:26)
    at Object.internals.implementation [as bell] (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bell/lib/index.js:76:25)
    at internals.Auth.strategy (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/hapi/lib/auth.js:51:43)
    at internals.Plugin._applyChild (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/hapi/lib/plugin.js:584:19)
    at Object.auth.strategy (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/hapi/lib/plugin.js:64:54)
    at /Users/lfsmoura/Dropbox/workspace/rpgstudio/src/web.js:63:21
    at tryCatcher (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/lfsmoura/Dropbox/workspace/rpgstudio/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)

My node is 6.2.2 and the package versions are:

rpgstudio: (master)$ npm ls
├── angular@1.5.7
├── angular-resource@1.5.7
├── angular-route@1.5.7
├─┬ bell@7.9.1
│ ├── boom@3.2.2
│ ├── cryptiles@3.0.1
│ ├── hoek@4.0.1
│ ├─┬ joi@8.4.2
│ │ ├── isemail@2.2.0
│ │ └── topo@2.0.1
│ └── wreck@8.0.0
├── bootstrap@4.0.0-alpha.2
├─┬ hapi@13.3.0
│ ├── accept@2.1.0
│ ├── ammo@2.0.0
│ ├── boom@3.1.2
│ ├── call@3.0.0
│ ├─┬ catbox@7.1.0
│ │ └── joi@7.3.0
│ ├── catbox-memory@2.0.1
│ ├── cryptiles@3.0.0
│ ├─┬ heavy@4.0.0
│ │ └── joi@7.3.0
│ ├── hoek@3.0.4
│ ├── iron@4.0.0
│ ├── items@2.0.0
│ ├─┬ joi@8.0.4
│ │ ├── isemail@2.1.0
│ │ └── moment@2.12.0
│ ├── kilt@2.0.0
│ ├─┬ mimos@3.0.0
│ │ └── mime-db@1.22.0
│ ├── peekaboo@2.0.0
│ ├── shot@3.0.1
│ ├─┬ statehood@4.0.0
│ │ └── joi@7.3.0
│ ├─┬ subtext@4.0.0
│ │ ├── content@3.0.0
│ │ ├─┬ pez@2.0.1
│ │ │ ├── b64@3.0.0
│ │ │ └─┬ nigel@2.0.0
│ │ │   └── vise@2.0.0
│ │ └── wreck@7.0.2
│ └── topo@2.0.0
├─┬ hapi-auth-cookie@6.1.1
│ ├── hoek@3.0.4
│ └── joi@7.3.0
├─┬ hapi-sequelize@2.2.4
│ ├── hoek@2.16.3
│ └─┬ sqlizr@1.2.0
│   └─┬ glob@5.0.15
│     ├─┬ inflight@1.0.5
│     │ └── wrappy@1.0.2
│     ├── inherits@2.0.1
│     ├─┬ minimatch@3.0.2
│     │ └─┬ brace-expansion@1.1.5
│     │   ├── balanced-match@0.4.1
│     │   └── concat-map@0.0.1
│     ├── once@1.3.3
│     └── path-is-absolute@1.0.0
├─┬ inert@3.2.1
│ ├─┬ ammo@1.0.1
│ │ ├── boom@2.10.1
│ │ └── hoek@2.16.3
│ ├── boom@2.10.1
│ ├── hoek@2.16.3
│ ├── items@1.1.1
│ ├─┬ joi@6.10.1
│ │ ├── isemail@1.2.0
│ │ └── topo@1.1.0
│ └── lru-cache@2.7.3
├── jquery@2.2.4
├── lodash@4.13.1
├─┬ pg@4.5.6
│ ├── buffer-writer@1.0.1
│ ├── generic-pool@2.4.2
│ ├── packet-reader@0.2.0
│ ├── pg-connection-string@0.1.3
│ ├─┬ pg-types@1.11.0
│ │ ├── ap@0.2.0
│ │ ├── postgres-array@1.0.0
│ │ ├── postgres-bytea@1.0.0
│ │ ├── postgres-date@1.0.2
│ │ └─┬ postgres-interval@1.0.2
│ │   └── xtend@4.0.1
│ ├─┬ pgpass@0.0.3
│ │ └─┬ split@0.3.3
│ │   └── through@2.3.8
│ └── semver@4.3.6
├── phaser@2.5.0
├─┬ sequelize@3.23.4
│ ├── bluebird@3.4.1
│ ├── depd@1.1.0
│ ├── dottie@1.1.1
│ ├── inflection@1.10.0
│ ├── lodash@4.12.0
│ ├── moment@2.13.0
│ ├── moment-timezone@0.5.4
│ ├── node-uuid@1.4.7
│ ├─┬ retry-as-promised@2.0.1
│ │ └─┬ debug@2.2.0
│ │   └── ms@0.7.1
│ ├── semver@5.2.0
│ ├── shimmer@1.1.0
│ ├─┬ terraformer-wkt-parser@1.1.0
│ │ └── terraformer@1.0.5
│ ├── toposort-class@1.0.1
│ ├── validator@5.4.0
│ └── wkx@0.2.0
├── tether@1.3.2
└── uuid@2.0.2

I looked at hoek code and the error is in this line

    seen = seen || new Map();

What is strage because this works in the REPL. Does the package use a different node version? What can I do to solve this?

**Comment by Marsup** [comment]
Something is probably messing with the globals. Edit hoek and try to `console.log(Map.toString())` see if it's a native.

**Comment by lfsmoura** [comment]
I'm really sorry it was a problem with my code. Thank you so much!
