### ISSUE TITLE
Github login failling silently

### ISSUE THREAD

**Issue by ThiagoMiranda** [hapijs/bell#262]
Hello

I´m trying to reproduce this [tutorial](https://www.sitepoint.com/oauth-integration-using-hapi/) but it´s giving me a Internal Server error ( response 500 ) without any details in my console.

This happens when github redirects to my login page using these parameters:
https://github.com/login/oauth/authorize?client_id=xxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth%2Fgithubauth&scope=user&state=3b213ab7da451f7d1725896972aa3fb155177fa0e0169339f70439d6f0ff38b9
--->
localhost:9000/auth/githubauth?code=5df8143df0b76f335f21&state=82160025caa888a5a399579c2328c2567595586ea0b33104377d60356531a121&refresh=1

My code is:
```javascript
var bellAuthOptions = {
    provider: 'github',
    password: 'github-encryption-password-for-playerground', //Password used for encryption
    clientId: process.env.GITHUB_CLIENT_ID,//'YourAppId',
    clientSecret: process.env.GITHUB_CLIENT_SECRET,//'YourAppSecret',
    isSecure: false
};

server.auth.strategy('github-oauth', 'bell', bellAuthOptions);]

server.route({
    method: ['GET', 'POST'],
    path: '/auth/githubauth',
    config: {
        handler: function(request, reply) {
                                       if (request.auth.isAuthenticated) {

        request.auth.session.set(request.auth.credentials);
        return reply('Hello ' + request.auth.credentials.profile.displayName);
    }

   reply('Not logged in...').code(401);
                        },
        auth: 'github-oauth'
    }
});
```

Another thing:
When I pass optional to a route it gives me an request.auth.error:
```javascript
{ isAuthenticated: false,
  credentials: null,
  artifacts: null,
  strategy: null,
  mode: 'optional',
  error: 
   { Error: Missing authentication}
```
Is it normal?

Thanks!

**Comment by ThiagoMiranda** [comment]
Update:

Changed the auth options to:
`				auth: {
                	strategy: 'github-oauth',
               	 	mode: 'try'
            	}`

Now it´s redirecting correctly but it´s giving me an error:

```javascript
{ isAuthenticated: false,
  credentials: undefined,
  artifacts: undefined,
  strategy: 'github-oauth',
  mode: 'try',
  error: 
   { Error: Missing github request token cookie
       at Object.internals.refreshRedirect (/Users/tmiranda/Development/sambatech/react/node_modules/bell/lib/oauth.js:318:27)
       at Object.authenticate (/Users/tmiranda/Development/sambatech/react/node_modules/bell/lib/oauth.js:204:30)
       at request._protect.run (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/auth.js:336:34)
       at internals.Protect.run (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/protect.js:62:12)
       at execute (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/auth.js:332:30)
       at authenticate (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/auth.js:318:21)
       at internals.Auth._authenticate (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/auth.js:226:19)
       at internals.Auth.authenticate (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/auth.js:197:17)
       at each (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/request.js:380:16)
       at iterate (/Users/tmiranda/Development/sambatech/react/node_modules/items/lib/index.js:36:13)
       at done (/Users/tmiranda/Development/sambatech/react/node_modules/items/lib/index.js:28:25)
       at Hoek.once (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/protect.js:52:16)
       at wrapped (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/node_modules/hoek/lib/index.js:871:20)
       at done (/Users/tmiranda/Development/sambatech/react/node_modules/items/lib/index.js:31:25)
       at finalize (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/lib/request.js:400:24)
       at Function.wrapped [as _next] (/Users/tmiranda/Development/sambatech/react/node_modules/Hapi/node_modules/hoek/lib/index.js:871:20)
     data: undefined,
     isBoom: true,
     isServer: true,
     output: { statusCode: 500, payload: [Object], headers: {} },
     reformat: [Function] } 
   }
```

**Comment by ThiagoMiranda** [comment]
I've misunderstood the whole thing. Now it's working.
Sorry about the issue and thanks for the module!

**Comment by conradkleinespel** [comment]
@ThiagoMiranda Do you remember what the issue was ? I am experiencing the same thing you were experiencing.

**Comment by conradkleinespel** [comment]
What fixed this issue for me was setting the `location` to the path of the auth route (and configuring this on the Github developer dashboard.

```js
server.auth.strategy('github', 'bell', {
    provider: 'github',
    password: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    clientId: '...',
    clientSecret: '...',
    isSecure: false,
    location: 'http://localhost:8000/login/github' // <== this
  })

  server.route({
    method: ['GET', 'POST'],
    path: '/login/github', // <== this
    config: {
      auth: {
        strategy: 'github',
        mode: 'try'
      },
      handler: function (request, reply) {
            ...
      }
    }
  })
```
