### ISSUE TITLE
Failed obtaining facebook access token :(

### ISSUE THREAD

**Issue by doron2402** [hapijs/bell#302]
Hi,

- I've used the example
- Made sure `isSecure` is false
- added localhost and a mock domain to `Valid OAuth redirect URIs` on facebook

My feeling is that my FB configuration are off, but happy to hear you guys feedback.

Thanks,
- Doron.
 
```
provider: 'facebook',
      password: 'cookie_encryption_password_secure',
      isSecure: false,
      clientId: FACEBOOK_CLIENT_ID,
      clientSecret: FACEBOOK_CLIENT_SECRET,
      location: 'http://localhost:3000'

```

here's the stack:

```{ Error: Failed obtaining facebook access token
    at Wreck.post (......./node_modules/bell/lib/oauth.js:248:35)
    at read (........../node_modules/wreck/lib/index.js:523:20)
    at finish (.................../node_modules/wreck/lib/index.js:344:20)
    at wrapped (.../node_modules/hoek/lib/index.js:871:20)
    at onReaderFinish (......./node_modules/wreck/lib/index.js:415:16)
    at g (events.js:291:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:488:14)
    at endWritable (_stream_writable.js:498:3)
  data: <Buffer 7b 22 65 72 72 6f 72 22 3a 7b 22 6d 65 73 73 61 67 65 22 3a 22 45 72 72 6f 72 20 76 61 6c 69 64 61 74 69 6e 67 20 76 65 72 69 66 69 63 61 74 69 6f 6e ... >,
  isBoom: true,
  isServer: true,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }
Failed obtaining facebook access token
```

When I'm getting redirect to facebook that's the error message I'm getting:

```
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
```

**Comment by doron2402** [comment]
found the issue facebook settings.. 👎

**Comment by angad94-14** [comment]
How did you solve this issue? I'm facing the same issue and can't seem to figure it out

**Comment by doron2402** [comment]
@angad94-14 it's under the app settings not really sure what I have to change
