### ISSUE TITLE
Investigate why boom 4.3+ breaks our tests

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#306]
Specifically: `./node_modules/.bin/lab -i 64 -m 0 -v`
Returns
```
Bell
  Client
    _request()
      ✖ 64) errors on failed request


Failed tests:

  64) Bell Client _request() errors on failed request:

      Cannot provide statusCode or message with boom error

      at Object.exports.assert (/Users/ldespla/bell/node_modules/hoek/lib/index.js:736:11)
      at Object.exports.wrap (/Users/ldespla/bell/node_modules/boom/lib/index.js:76:10)
      at Object.internals.serverError (/Users/ldespla/bell/node_modules/boom/lib/index.js:393:25)
      at Object.exports.internal (/Users/ldespla/bell/node_modules/boom/lib/index.js:385:22)
      at Wreck.(anonymous function) (/Users/ldespla/bell/lib/oauth.js:416:34)
      at process.nextTick (/Users/ldespla/bell/node_modules/hoek/lib/index.js:854:22)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by jmonster** [comment]
fwiw I'm also encountering this exact same error in my own project after upgrading; landed here hoping for a solution 😁

**Comment by arb** [comment]
https://github.com/hapijs/boom/commit/544cc13db7c7fc99b43bbb8eb1ce2ce57f2c78db

I didn't really have much to do with this initial change. Here is where the initial change happened
https://github.com/hapijs/boom/commit/3aa4a8c05e88646c22edac2e876411d8d3d61b06#commitcomment-21496008

**Comment by jmonster** [comment]
I didn't mean to suggest Boom was at fault :) it might be surfacing other problems.
