### ISSUE TITLE
isSecure not working with http/2

### ISSUE THREAD

**Issue by jerome724** [hapijs/bell#309]
```
Debug: internal, error
    Error: Invalid setting  - isSecure must be set to false for non-https server
    at Object.authenticate (C:\Users\jerom\Documents\programming\Project\node_modules\bell\lib\oauth.js:158:31)
    at request._protect.run (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\auth.js:336:34)
    at module.exports.internals.Protect.internals.Protect.run (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\protect.js:59:12)
    at Object.execute (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\auth.js:332:30)
    at Object.authenticate (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\auth.js:318:21)
    at module.exports.internals.Auth.internals.Auth._authenticate (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\auth.js:226:19)
    at internals.Auth.authenticate (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\auth.js:197:17)
    at each (C:\Users\jerom\Documents\programming\Project\node_modules\hapi\lib\request.js:382:16)
    at iterate (C:\Users\jerom\Documents\programming\Project\node_modules\items\lib\index.js:36:13)
    at done (C:\Users\jerom\Documents\programming\Project\node_modules\items\lib\index.js:28:25)
```

But my server runs on an http/2 listener, https is available. It is only working when i set ``isSecure:`` to ``false``, not 100% sure if it is a problem with http/2, since i'm using nginx as an reverse proxy, but my tests seems to be ok https://securityheaders.io/?q=https%3A%2F%2Fpreview.jerome724.com&followRedirects=on

```js
// ssl certificate
const certificate = fs.readFileSync('./certificates/jerome724.com.pfx');

// http2 listener
const http2Listener = http2.createServer({
	pfx: certificate
});

server.connection({
	listener: http2Listener,
	port: config.server.port,
	labels: config.server.labels
});
```

Any idea how i could fix that?

**Comment by jerome724** [comment]
okay, got a ``fix``, not really a fix, was my fault. I had to set ``tls: true`` in my ``server.connection``, now it is working fine!

closed and thanks for the plugin 👍
