### ISSUE TITLE
Missing azuread request token cookie

### ISSUE THREAD

**Issue by wy193777** [hapijs/bell#324]
Initialized with:
```javascript
server.auth.strategy('azuread', 'bell', {
        provider: 'azuread',
        password: config.password,
        clientId: config.clientId,
        clientSecret: config.clientSecret,
        config: {tenant: config.tenant},
});
```

Error Stack:
```
[error] message: Missing azuread request token cookie, stack: Error: Missing azuread request token cookie
    at Object.internals.refreshRedirect (/home/shenghang/nvidia/node_modules/bell/lib/oauth.js:320:27)
    at Object.authenticate (/home/shenghang/nvidia/node_modules/bell/lib/oauth.js:204:30)
    at request._protect.run (/home/shenghang/nvidia/node_modules/hapi/lib/auth.js:336:34)
    at module.exports.internals.Protect.internals.Protect.run (/home/shenghang/nvidia/node_modules/hapi/lib/protect.js:60:12)
    at Object.execute (/home/shenghang/nvidia/node_modules/hapi/lib/auth.js:332:30)
    at Object.authenticate (/home/shenghang/nvidia/node_modules/hapi/lib/auth.js:318:21)
    at module.exports.internals.Auth.internals.Auth._authenticate (/home/shenghang/nvidia/node_modules/hapi/lib/auth.js:226:19)
    at internals.Auth.authenticate (/home/shenghang/nvidia/node_modules/hapi/lib/auth.js:197:17)
    at each (/home/shenghang/nvidia/node_modules/hapi/lib/request.js:401:16)
    at iterate (/home/shenghang/nvidia/node_modules/items/lib/index.js:36:13)
    at done (/home/shenghang/nvidia/node_modules/items/lib/index.js:28:25)
    at request.connection.states.parse (/home/shenghang/nvidia/node_modules/hapi/lib/route.js:314:20)
    at Items.serial (/home/shenghang/nvidia/node_modules/hapi/node_modules/statehood/lib/index.js:249:16)
    at done (/home/shenghang/nvidia/node_modules/items/lib/index.js:31:25)
    at Items.serial (/home/shenghang/nvidia/node_modules/hapi/node_modules/statehood/lib/index.js:189:20)
    at iterate (/home/shenghang/nvidia/node_modules/items/lib/index.js:36:13)
```

The problem seems comes from the "refresh=1" on redirected url.

**Comment by wy193777** [comment]
Finally find the reason, isSecure must be set false. Maybe has a more detailed error message?
