### ISSUE TITLE
Auth0 with isSecure=true - Incorrect auth0 state parameter 

### ISSUE THREAD

**Issue by panigrah** [hapijs/bell#352]
Hi all,

I am using hapi17 and bell 9.1.0 with Auth0. After I authenticate with auth0 the redirect back to results in the error:

```
Incorrect auth0 state parameter 
at Object.authenticate (/app/server/node_modules/bell/lib/oauth.js:232:43
at module.exports.internals.Manager.execute (/app/server/node_modules/hapi/lib/toolkit.js:35:106
at module.exports.internals.Auth._authenticate (/app/server/node_modules/hapi/lib/auth.js:242:58
at authenticate (/app/server/node_modules/hapi/lib/auth.js:217:21
at module.exports.internals.Request._lifecycle (/app/server/node_modules/hapi/lib/request.js:261:62
at <anonymous>
```

This only happens if the `isSecure` flag is set to true. Am using https and `forceHttps` is set to true. Is it okay to leave `isSecure=false` if on https?

**Comment by sholladay** [comment]
I am using Auth0 and bell 9.1.0 with `isSecure: true` and not having any problems. So maybe it's something else about your setup. Check out [hapi-doorkeeper](https://github.com/sholladay/hapi-doorkeeper) to see how I'm doing it.

**Comment by panigrah** [comment]
Thank you @sholladay  will keep looking into other setup.
