### ISSUE TITLE
Twitter example is not working

### ISSUE THREAD

**Issue by ciaoben** [hapijs/bell#425]
Hi, thanks for the great work in this library. It is really useful!
I am trying to set up a twitter auth flow, but simply following the simple example it does not seem to work. Here my basic code:

```
'use strict';

const Hapi = require('@hapi/hapi');
const Bell = require('@hapi/bell');

const init = async () => {
  const server = Hapi.server({port: 3333, host: 'localhost'});

  // Register bell with the server
  await server.register(Bell);

  server.auth.strategy('twitter', 'bell', {
    provider: 'twitter',
    password: 'test_test',
    clientId: 'my_consumer_api_key',
    clientSecret: 'my_consumer_api_key_secret',
    isSecure: false 
  });


  server.route({
    method: 'GET', // Must handle both GET and POST
    path: '/bell/door', // The callback endpoint registered with the provider
    options: {
      auth: 'twitter',
      handler: function(request, h) {

        if (!request.auth.isAuthenticated) {
          return `Authentication failed due to: ${request.auth.error.message}`;
        }

        return h.redirect('/home');
      }
    }
  });

  server.events.on('request', (request, event, tags) => {
    if (event.channel === 'error') {
      console.dir(event.error.data, 4);
    }
  });

  await server.start();
  console.log('Server running on %s', server.info.uri);
};

// process.on('unhandledRejection', err => {
//   console.log(err);
//   process.exit(1);
// });

init();

```

And here is the config of my app:

![Screenshot 2019-08-29 at 09 41 21](https://user-images.githubusercontent.com/4526061/63920773-d82ca400-ca41-11e9-8453-8a018468e258.png)

But when I go to `http://localhost:3333/bell/door` with my browser I get this error:

```
 { Error: Failed obtaining twitter temporary credentials
    at exports.Client.internals.Client.internals.Client._request (/Users/ben/pro/tmp/authy/node_modules/@hapi/bell/lib/oauth.js:453:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  data:
   { Error: Response Error: 403 Forbidden
       at internals.Client._shortcut (/Users/ben/pro/tmp/authy/node_modules/@hapi/wreck/lib/index.js:635:11)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     data:
      { isResponseError: true,
        headers: [Object],
        res: [IncomingMessage],
        payload:
         <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 55 54 46 2d 38 22 3f 3e 3c 65 72 72 6f 72 73 3e 3c 65 72 72 ... > },
     isBoom: true,
     isServer: false,
     output: { statusCode: 403, payload: [Object], headers: {} },
     reformat: [Function],
     typeof: [Function: Error] },
  isBoom: true,
  isServer: true,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  typeof: [Function: internal] }
```

What am I doing wrong?

**Comment by hueniverse** [comment]
Try grabbing that payload buffer and converting it `toString()`. That should contain the error from Twitter with some clues.
