### ISSUE TITLE
Issue with the meetup provider

### ISSUE THREAD

**Issue by qraynaud** [hapijs/bell#458]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Core
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 13.11.0
* *module version with issue*: 12.0.0
* *last module version without issue*: N/A
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: none

#### What are you trying to achieve or the steps to reproduce?

I'm trying to make a simple oauth login with meetup servers. Nothing fancy here.

#### What was the result you got?

Some logins attempt are working as expected, others are not. When they fail, here is my stack (with a console.log() added in your code to get more information on the issue), as produced by the `err-tree` module:
```
[0] Error: Incorrect meetup state parameter − code 500
[0] |
[0] |  /www/node_modules/@hapi/bell/lib/oauth.js:
[0] |  246.         const requestState = request.query.state || '';
[0] |  247.         console.log('####', state.nonce, internals.nonceLength, requestState.length, requestState.substr(0, Math.min(requestState.length, internals.nonceLength)))
[0] |  248.         if (state.nonce !== requestState.substr(0, Math.min(requestState.length, internals.nonceLength))) {
[0] |  249.             return h.unauthenticated(Boom.internal('Incorrect ' + name + ' state parameter'), { credentials });
[0] |  250.         }
[0] |  251. 
[0] |  252.         const query = {
[0] |
[0] |  Trace:
[0] |    at Object.authenticate (/www/node_modules/@hapi/bell/lib/oauth.js:249:43)
[0] |    at exports.Manager.execute (/www/node_modules/@hapi/hapi/lib/toolkit.js:53:36)
[0] |    at module.exports.internals.Auth._authenticate (/www/node_modules/@hapi/hapi/lib/auth.js:258:58)
[0] |    at authenticate (/www/node_modules/@hapi/hapi/lib/auth.js:234:21)
[0] |    at Request._lifecycle (/www/node_modules/@hapi/hapi/lib/request.js:365:68)
[0] |    at async Request._execute (/www/node_modules/@hapi/hapi/lib/request.js:274:9
```

And here are the information logged by the `console.log()` call:
```
#### 0GCzQ6XHSrPSMIgfuWtA_M 22 22 0GCzQ6XHSrPSMIgfuWtA M
```

As you can see, the nonce is not equal to the `requestState`. The `_` character is replaced by what seems to be a space. All calls with a state containing an `_` are failing. That's sad. This seems to be a bug caused by the meetup servers altering the `state` parameter (they should not do that!).

I'll try to write to them, but I don't expect them to be very responsive about this issue though. Is there a way to fix this on `bell's` side?

**Comment by qraynaud** [comment]
Right now I made this shitty-workaround patch that solves the issue:
```diff
diff --git a/node_modules/@hapi/bell/lib/oauth.js b/node_modules/@hapi/bell/lib/oauth.js
index e6581df..b2bd061 100755
--- a/node_modules/@hapi/bell/lib/oauth.js
+++ b/node_modules/@hapi/bell/lib/oauth.js
@@ -177,7 +177,10 @@ exports.v2 = function (settings) {
         if (!request.query.code) {
             credentials.query = request.query;
 
-            const nonce = Cryptiles.randomString(internals.nonceLength);
+            let nonce = null
+            do {
+              nonce = Cryptiles.randomString(internals.nonceLength);
+            } while (nonce.indexOf('_') >= 0)
             const query = internals.resolveProviderParams(request, settings.providerParams);
 
             if (settings.allowRuntimeProviderParams) {
```
